parameters:
    app.name: app
    app.version: 0.0.1

services:
    app.command.test:
        class: App\Command\TestCommand
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: console.command }
